import createStyles from '@mui/styles/createStyles';
import makeStyles from '@mui/styles/makeStyles';
import { primaryLighter } from '../../assets/themes/vaal-theme';

export const useStyles = makeStyles((theme) =>
  createStyles({
    root: {
      padding: theme.spacing(3),
      height: '100%',
      overflowY: 'auto',
    },
    header: {
      marginBottom: theme.spacing(3),
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    title: {
      color: primaryLighter,
      fontWeight: 'bold',
    },
    dropdown: {
      minWidth: '200px',
      marginRight: theme.spacing(2),
    },
    refreshBtn: {
      color: '#ffffff',
      borderColor: 'rgba(240, 192, 90, 0.4)',
      '&:hover': {
        borderColor: primaryLighter,
        background: 'rgba(240, 192, 90, 0.1)',
      },
    },
    gridContainer: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gridTemplateRows: 'auto auto auto auto',
      gap: theme.spacing(2),
      width: '100%',
      maxWidth: '460px',
      margin: '0 auto',
      background: 'rgba(15, 15, 15, 0.65)',
      padding: theme.spacing(2),
      borderRadius: '12px',
      border: '1px solid rgba(240, 192, 90, 0.15)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.6)',
      backdropFilter: 'blur(10px)',
    },
    equipSlot: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'rgba(5, 5, 5, 0.5)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '8px',
      padding: theme.spacing(1),
      minHeight: '90px',
      position: 'relative',
      transition: 'all 0.25s ease',
      cursor: 'pointer',
      '&:hover': {
        borderColor: 'rgba(240, 192, 90, 0.6)',
        boxShadow: '0 0 10px rgba(240, 192, 90, 0.2)',
      },
    },
    slotWeapon1: {
      gridRow: 'span 2',
      minHeight: '190px',
    },
    slotWeapon2: {
      gridRow: 'span 2',
      minHeight: '190px',
    },
    itemIcon: {
      maxHeight: '80%',
      maxWidth: '80%',
      objectFit: 'contain',
      filter: 'drop-shadow(0 2px 6px rgba(0,0,0,0.8))',
    },
    slotLabel: {
      fontSize: '0.75rem',
      color: theme.palette.text.secondary,
      position: 'absolute',
      bottom: '4px',
      pointerEvents: 'none',
      textTransform: 'uppercase',
      letterSpacing: '1px',
    },
    flaskContainer: {
      display: 'flex',
      justifyContent: 'center',
      gap: theme.spacing(1.2),
      marginTop: theme.spacing(2),
      width: '100%',
      maxWidth: '460px',
      margin: '20px auto 0 auto',
      background: 'rgba(15, 15, 15, 0.65)',
      padding: theme.spacing(1.5),
      borderRadius: '10px',
      border: '1px solid rgba(240, 192, 90, 0.15)',
    },
    flaskSlot: {
      flex: 1,
      height: '80px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'rgba(5, 5, 5, 0.5)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '6px',
      position: 'relative',
      cursor: 'pointer',
      transition: 'all 0.25s ease',
      '&:hover': {
        borderColor: 'rgba(240, 192, 90, 0.6)',
      },
    },
    rarityUnique: { borderColor: '#af6025 !important' },
    rarityRare: { borderColor: '#ebd26b !important' },
    rarityMagic: { borderColor: '#8888ff !important' },
    rarityNormal: { borderColor: '#ffffff !important' },
    tooltipRoot: {
      background: 'rgba(10, 10, 10, 0.95) !important',
      border: '1px solid rgba(240, 192, 90, 0.4) !important',
      borderRadius: '8px !important',
      boxShadow: '0 4px 20px rgba(0,0,0,0.8) !important',
      padding: '12px !important',
      maxWidth: '320px !important',
    },
    tooltipName: {
      fontWeight: 'bold',
      color: '#ebd26b',
      borderBottom: '1px solid rgba(255,255,255,0.1)',
      paddingBottom: '4px',
      marginBottom: '6px',
    },
    tooltipType: {
      color: '#ffffff',
      fontSize: '0.85rem',
      marginBottom: '6px',
    },
    tooltipMod: {
      color: '#8888ff',
      fontSize: '0.8rem',
      lineHeight: '1.4',
    },
    panelCard: {
      background: 'rgba(20, 20, 20, 0.6) !important',
      border: '1px solid rgba(255, 255, 255, 0.05) !important',
      borderRadius: '12px !important',
      padding: theme.spacing(3.5),
      height: '100%',
      backdropFilter: 'blur(10px)',
    },
    sectionTitle: {
      color: primaryLighter,
      fontWeight: 'bold',
      marginBottom: theme.spacing(2),
      borderBottom: '2px solid rgba(240, 192, 90, 0.2)',
      paddingBottom: theme.spacing(1),
    },
    passiveCountText: {
      fontSize: '2.5rem',
      fontWeight: 'bold',
      color: '#ebd26b',
      textAlign: 'center',
      margin: '20px 0',
    },
    skillRow: {
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(1.5),
      padding: theme.spacing(1.5),
      background: 'rgba(0,0,0,0.3)',
      borderRadius: '6px',
      marginBottom: theme.spacing(1),
      borderLeft: '3px solid rgba(240,192,90,0.6)',
    },
    gemIcon: {
      width: '28px',
      height: '28px',
      objectFit: 'contain',
    },
    gemName: {
      fontWeight: 500,
      color: '#ffffff',
      fontSize: '0.9rem',
    },
    supportName: {
      color: '#8888ff',
      fontSize: '0.8rem',
    },
  })
);
